### ISSUE TITLE
Is it a downgrade?

### ISSUE THREAD

**Issue by imsturmdernacht** [stfnhmplr/homebridge-synology#19]
Hey,

the new release number is smaller that the last one?

The new version 0.0.3 is no longer working. Before updating everything worked fine. Do we have to change something in config.json?

[Fri Mar 10 2017 20:56:23 GMT+0100 (CET)] ====================
[Fri Mar 10 2017 20:56:23 GMT+0100 (CET)] ERROR LOADING PLUGIN homebridge-synology:
[Fri Mar 10 2017 20:56:23 GMT+0100 (CET)] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
[Fri Mar 10 2017 20:56:23 GMT+0100 (CET)] ====================

Regards, Oli

**Comment by stfnhmplr** [comment]
No, thats an mistake. Should be version 0.2.1 Next update will fix this.

i think you are using an old version of node. the older versions does not run in strict mode, so let and const are not supported. changed back to var should fix it. update will be published in the next hours.

**Comment by imsturmdernacht** [comment]
Hey,

just wanna give you an update. Yes, I'm using an old version 4 of node js on a pi. But in relase 0.2.2 everything is fine again. Good job and a lot of thanks.

Regards, Oli
