### ISSUE TITLE
Error loging to diskstation

### ISSUE THREAD

**Issue by nebuchar** [stfnhmplr/homebridge-synology#22]
Hi,

When it tries to connect to diskstation, it throws this error:
```
/opt/node/lib/node_modules/homebridge-synology/lib/synology.js:66
                    that.auth.sid = json.data.sid;
                                             ^

TypeError: Cannot read property 'sid' of undefined
    at Request._callback (/opt/node/lib/node_modules/homebridge-synology/lib/synology.js:66:46)
    at Request.self.callback (/opt/node/lib/node_modules/homebridge-synology/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/node/lib/node_modules/homebridge-synology/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/homebridge-synology/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

I'm using DSM 6.1.1-15101 Update 2

Thanks

**Comment by stfnhmplr** [comment]
Hi,

did you check your login credentials? Do you use 2FA? The error means, that your diskstation does not return a sid to use the synology api. Can you post your config.json please?

**Comment by stfnhmplr** [comment]
Hey there!

I close this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. If the issue still exists, let me know with a comment and i will reopen it.

Thanks!
