### ISSUE TITLE
Crashes with 214se and dsm6 rc

### ISSUE THREAD

**Issue by guybrushix** [stfnhmplr/homebridge-synology#3]
403 Forbidden
    ^

SyntaxError: Unexpected token F
    at Object.parse (native)
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-synology/lib/synology.js:165:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-synology/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-synology/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-synology/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)

**Comment by guybrushix** [comment]
it seems the webapi has changed in DSM6

**Comment by stfnhmplr** [comment]
thank you. Yes, I think so, too. but I didn't find any documentation for DSM6

**Comment by guybrushix** [comment]
Maybe contact the Synology Support ?

**Comment by cbrandlehner** [comment]
I tested with DSM 6.0-7307 / release candidate of DSM 6.0 and can confirm that the API has changed.

**Comment by TheHavocHero** [comment]
I have a similar issue with DSM 6 beta. As soon as I pull up the accessory in my app and it tries to read the temp and other variables, the server crashes. 

```
[3/23/2016, 5:43:59 PM] [Diskstation] current power state is: true stdout 
17:44:00 undefined:1 stderr
17:44:00 403 Forbidden stderr
17:44:00   ^ stderr
17:44:00 stderr
17:44:00 SyntaxError: Unexpected token F stderr
17:44:00 at Object.parse (native) stderr
17:44:00 at null.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-synology/lib/synology.js:165:29) stderr
17:44:00 at Request.self.callback (/usr/lib/node_modules/homebridge-synology/node_modules/request/request.js:199:22) stderr
17:44:00 at emitTwo (events.js:100:13) stderr
17:44:00 at Request.emit (events.js:185:7) stderr
17:44:00 at Request.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-synology/node_modules/request/request.js:1036:10) stderr
17:44:00 at emitOne (events.js:95:20) stderr
17:44:00 at Request.emit (events.js:182:7) stderr
17:44:00 at IncomingMessage.&lt;anonymous&gt; (/usr/lib/node_modules/homebridge-synology/node_modules/request/request.js:963:12) stderr
17:44:00 at emitNone (events.js:85:20)
```

**Comment by combchris** [comment]
Yea I have having the same problem as well, I was running the 6.0 RC beta, However Today DSM 6.0 went live so hopefully this will be fixed. This would have been a great feature to add to my Homekit Line-up

**Comment by stfnhmplr** [comment]
**New version with support for DSM 6 is available.**
