### ISSUE TITLE
unexpected token and homebridge crashes

### ISSUE THREAD

**Issue by darkoddio** [stfnhmplr/homebridge-synology#8]
hi
DS416, DSM 6.0.2, Raspbian
after installing and configuring homebridge-synoloy this happens when starting homebridge:

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at null.<anonymous> (/usr/lib/node_modules/homebridge-synology/lib/synology.js:59:33)
    at Request.self.callback (/usr/lib/node_modules/homebridge-synology/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-synology/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-synology/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
```

**Comment by stfnhmplr** [comment]
seems to be a problem with the login to your diskstation. can you check your login credentials and post your config.json here?
