### ISSUE TITLE
Not installing on Homebridge Docker

### ISSUE THREAD

**Issue by mgoeppl** [stfnhmplr/homebridge-synology#85]
**Describe Your Problem:**
Plugin does not install, see error below. 

**Logs:**

```
USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-synology@0.5.0

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
npm ERR! No user exists for uid 1000
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-01-10T19_44_24_992Z-debug-0.log

Operation failed. Please review log for details.```

**Plugin Config:**

```json
        {
            "accessory": "Synology",
            "name": "Diskstation",
            "host": "192.168.3.2",
            "mac": "90:23:45:56:2C",
            "port": 5001,
            "protocol": "https",
            "username": "synoadmin",
            "password": "synoadmin",
            "version": "6.2.2",
            "otp": "ISDHIAGDUYEGU***",
            "startupTime": 60,
            "shutdownTime": 60,
            "disabled": [
                "switch"
            ]
        }```

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v4.50.2
* **Node.js Version**: v18.13.0
* **NPM Version**: 8.19.3
* **Operating System**: Docker (Ubuntu Focal Fossa (20.04.5 LTS))

**Comment by Vaifranz** [comment]
Same problem, error 128

**PlugIn version**: 0.5.2
**Homebridge Version**: 4.50.2
**Nede.js Version**: 16.14.0
**Operating System**: Docker (Alpine Linux (3.12.9)) on Synology

Same problem with previous plugin. What do I do? Thanks

**Comment by ghost** [comment]
same issue here : 

```
74 verbose stack Error: An unknown git error occurred
74 verbose stack     at makeError (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
74 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
75 verbose cwd /homebridge
76 verbose Linux 6.2.10-x64v3-xanmod1
77 verbose node v18.13.0
78 verbose npm  v8.19.3
79 error code 128
80 error An unknown git error occurred
81 error command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
82 error No user exists for uid 1000
82 error fatal: Could not read from remote repository.
82 error
82 error Please make sure you have the correct access rights
82 error and the repository exists.
83 verbose exit 128
84 timing npm Completed in 2464ms
85 verbose unfinished npm timer reify 1680953773244
86 verbose unfinished npm timer reify:loadTrees 1680953773246
87 verbose code 128
```

and from root :

```
git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I figured out how to do it, if it helps anyone I will leave it written here.

You have to go into bash on the container and give this command from root:

**`hb-service add homebridge-synology`**

**Comment by rdenimal** [comment]
> same issue here :
> 
> ```
> 74 verbose stack Error: An unknown git error occurred
> 74 verbose stack     at makeError (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
> 74 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
> 75 verbose cwd /homebridge
> 76 verbose Linux 6.2.10-x64v3-xanmod1
> 77 verbose node v18.13.0
> 78 verbose npm  v8.19.3
> 79 error code 128
> 80 error An unknown git error occurred
> 81 error command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
> 82 error No user exists for uid 1000
> 82 error fatal: Could not read from remote repository.
> 82 error
> 82 error Please make sure you have the correct access rights
> 82 error and the repository exists.
> 83 verbose exit 128
> 84 timing npm Completed in 2464ms
> 85 verbose unfinished npm timer reify 1680953773244
> 86 verbose unfinished npm timer reify:loadTrees 1680953773246
> 87 verbose code 128
> ```
> 
> and from root :
> 
> ```
> git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> I figured out how to do it, if it helps anyone I will leave it written here.
> 
> You have to go into bash on the container and give this command from root:
> 
> **`hb-service add homebridge-synology`**

Thank you ! That worked for me too

**Comment by rdenimal** [comment]
> I figured out how to do it, if it helps anyone I will leave it written here.
> 
> You have to go into bash on the container and give this command from root:
> 
> **`hb-service add homebridge-synology`**

Thanks @fatez that worked for me too !

**Comment by dgauche** [comment]
> You have to go into bash on the container and give this command from root:
> 
> **`hb-service add homebridge-synology`**

This worked for me, but I first needed to upgrade npm with: 
`npm install -g`

**Comment by johannesscherbaum** [comment]
Still got the problem with this error:
```
ℹ CMD: npm --prefix "/volume1/homebridge" add homebridge-synology@latest
npm error code ENOENT
npm error syscall spawn git
npm error path git
npm error errno -2
npm error enoent An unknown git error occurred
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2025-01-18T08_18_16_248Z-debug-0.log
✖ Plugin installation failed as Command failed: npm --prefix "/volume1/homebridge" add homebridge-synology@latest.
```
