### ISSUE TITLE
ERR! code 128

### ISSUE THREAD

**Issue by Jamyz** [stfnhmplr/homebridge-synology#91]
**Describe The Bug:**
Cant install

**To Reproduce:**
Install Package homebridge-synology

**Expected behavior:**
Works without bug

**Logs:**

```
USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-synology@0.5.2

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
npm ERR! No user exists for uid 1000
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-05-01T10_19_16_852Z-debug-0.log

Operation failed. Please review log for details.
```
 /home/homebridge/.npm/_logs/2023-05-01T10_19_16_852Z-debug-0.log

```
root@raspberrypi:/homebridge $ cat /home/homebridge/.npm/_logs/2023-05-01T10_19_16_852Z-debug-0.log
0 verbose cli /opt/homebridge/bin/node /opt/homebridge/bin/npm
1 info using npm@8.19.3
2 info using node@v18.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/opt/homebridge/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 6ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/homebridge/.npmrc Completed in 4ms
10 timing config:load:project Completed in 29ms
11 timing config:load:file:/home/homebridge/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/homebridge/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 58ms
19 timing npm:load:configload Completed in 58ms
20 timing npm:load:mkdirpcache Completed in 3ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm install homebridge-synology@0.5.2
23 verbose argv "install" "--save" "homebridge-synology@0.5.2"
24 timing npm:load:setTitle Completed in 3ms
25 timing config:load:flatten Completed in 8ms
26 timing npm:load:display Completed in 14ms
27 verbose logfile logs-max:10 dir:/home/homebridge/.npm/_logs
28 verbose logfile /home/homebridge/.npm/_logs/2023-05-01T10_19_16_852Z-debug-0.log
29 timing npm:load:logFile Completed in 15ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 99ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing arborist:ctor Completed in 0ms
38 timing arborist:ctor Completed in 0ms
39 timing idealTree:init Completed in 966ms
40 timing idealTree:userRequests Completed in 5ms
41 silly idealTree buildDeps
42 silly fetch manifest homebridge-synology@0.5.2
43 http fetch GET 200 https://registry.npmjs.org/homebridge-synology 1045ms (cache revalidated)
44 silly placeDep ROOT homebridge-synology@0.5.2 OK for:  want: 0.5.2
45 silly fetch manifest @types/ping@^0.2.0
46 silly fetch manifest @types/wol@^1.0.0
47 silly fetch manifest axios@^0.21.1
48 silly fetch manifest syno@git+https://github.com/homeinstalator/syno.git
49 silly fetch manifest wol@^1.0.7
50 http fetch GET 200 https://registry.npmjs.org/axios 224ms (cache revalidated)
51 http fetch GET 200 https://registry.npmjs.org/wol 913ms (cache revalidated)
52 http fetch GET 200 https://registry.npmjs.org/@types%2fping 1015ms (cache revalidated)
53 http fetch GET 200 https://registry.npmjs.org/@types%2fwol 1623ms (cache revalidated)
54 timing idealTree:#root Completed in 2695ms
55 silly placeDep node_modules/homebridge-synology @types/ping@0.2.1 OK for: homebridge-synology@0.5.2 want: ^0.2.0
56 silly placeDep node_modules/homebridge-synology @types/wol@1.0.1 OK for: homebridge-synology@0.5.2 want: ^1.0.0
57 silly placeDep node_modules/homebridge-synology axios@0.21.4 OK for: homebridge-synology@0.5.2 want: ^0.21.1
58 silly placeDep node_modules/homebridge-synology syno@ OK for: homebridge-synology@0.5.2 want: git+https://github.com/homeinstalator/syno.git
59 silly placeDep node_modules/homebridge-synology wol@1.0.7 OK for: homebridge-synology@0.5.2 want: ^1.0.7
60 silly fetch manifest @types/node@*
61 silly fetch manifest follow-redirects@^1.14.0
62 http fetch GET 200 https://registry.npmjs.org/follow-redirects 91ms (cache revalidated)
63 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 121ms (cache revalidated)
64 timing idealTree:node_modules/homebridge-synology Completed in 194ms
65 timing idealTree:node_modules/homebridge-synology/node_modules/@types/ping Completed in 1ms
66 silly placeDep node_modules/homebridge-synology @types/node@18.16.3 OK for: @types/wol@1.0.1 want: *
67 timing idealTree:node_modules/homebridge-synology/node_modules/@types/wol Completed in 4ms
68 timing idealTree:node_modules/homebridge-synology/node_modules/@types/node Completed in 0ms
69 silly placeDep node_modules/homebridge-synology follow-redirects@1.15.2 OK for: axios@0.21.4 want: ^1.14.0
70 timing idealTree:node_modules/homebridge-synology/node_modules/axios Completed in 5ms
71 timing idealTree:node_modules/homebridge-synology/node_modules/follow-redirects Completed in 1ms
72 timing idealTree:node_modules/homebridge-synology/node_modules/syno Completed in 0ms
73 timing idealTree:node_modules/homebridge-synology/node_modules/wol Completed in 0ms
74 timing idealTree:buildDeps Completed in 2905ms
75 timing idealTree:fixDepFlags Completed in 10ms
76 timing idealTree Completed in 3892ms
77 timing command:install Completed in 3929ms
78 verbose stack Error: An unknown git error occurred
78 verbose stack     at makeError (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
78 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
78 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
79 verbose cwd /homebridge
80 verbose Linux 6.1.21-v8+
81 verbose node v18.13.0
82 verbose npm  v8.19.3
83 error code 128
84 error An unknown git error occurred
85 error command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
86 error No user exists for uid 1000
86 error fatal: Could not read from remote repository.
86 error
86 error Please make sure you have the correct access rights
86 error and the repository exists.
87 verbose exit 128
88 timing npm Completed in 4286ms
89 verbose unfinished npm timer reify 1682936357202
90 verbose unfinished npm timer reify:loadTrees 1682936357228
91 verbose code 128
92 error A complete log of this run can be found in:
92 error     /home/homebridge/.npm/_logs/2023-05-01T10_19_16_852Z-debug-0.log
```

**Environment:**
Docker
* **Plugin Version**:
homebridge-synology v0.5.2 (2023-03-04)
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.13.0
* **NPM Version**: 8.19.3
* **Operating System**: 
*PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

I try `hb-service add homebridge-synology` in bash container without succes

**Comment by Seexelas** [comment]
Hello,

I have a similar issue : 

homebridge@homebridge:/var/lib/homebridge $ hb-service add homebridge-synology
CMD: npm --prefix "/var/lib/homebridge" add homebridge-synology@latest
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2023-05-18T10_59_14_857Z-debug-0.log
✖ Plugin installation failed.

I'm running Homebridge on a LXC container on Proxmox. 

OS | Debian GNU/Linux Bullseye (11)
Node.js : v18.16.0

Here is the log file : 

[2023-05-18T10_59_14_857Z-debug-0.log](https://github.com/stfnhmplr/homebridge-synology/files/11507093/2023-05-18T10_59_14_857Z-debug-0.log)

Many thanks for the help.

**Comment by Seexelas** [comment]
I did some test, I'm able to install the plugin until the 3.1 👍 

![image](https://github.com/stfnhmplr/homebridge-synology/assets/64669806/b6fd09ec-6da7-44f1-b5db-7d08c95b53c6)

After the 4.0 beta and 4.0 final, I can't update.

If that can help.

**Comment by Marvin-Keller** [comment]
Same issue here on a raspberry pi 4 with homebridge installed as homebridge-service.

**Comment by semyonchetvertnyh** [comment]
Guys you have to install Git to fix the issue.

Instructions: https://github.com/homebridge/homebridge-syno-spk/wiki/DSM-7:-Install-git
